apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-nfs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  #persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/mnt/nginx-exposed/"
    server: 192.168.1.222       #this is our backend NFS server IP address
    readOnly: false