apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: postgresql-data-claim 
  namespace: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 10Gi # Sets volume size