apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-external-deployment
  namespace: nginx-exposed
  labels:
    app: nginx-external
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-ex
  template:
    metadata:
      labels:
        app: httpd-ex
    spec:
      volumes:
        - name: nginx-hdd
          persistentVolumeClaim:
            claimName: pvc-volume-nfs 
      containers:
        - name: httpd-exp
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html" #nginX default path => m.t
              name: nginx-hdd